apiVersion: apps/v1
kind: Deployment
metadata:
  name: localdev-keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localdev-keycloak
  template:
    metadata:
      labels:
        app: localdev-keycloak
    spec:
      containers:
        - name: keycloak
          image: keycloak/keycloak:26.2
          args:
            - start-dev
            - --import-realm
          env:
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              value: admin
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              value: admin
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL
              value: jdbc:postgresql://localdev-keycloak-postgres:5432/keycloak
            - name: KC_DB_USERNAME
              value: keycloak
            - name: KC_DB_PASSWORD
              value: keycloak
            - name: KC_HEALTH_ENABLED
              value: "true"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: realm-config
              mountPath: /opt/keycloak/data/import
          # readinessProbe:
          #   httpGet:
          #     path: /health/ready
          #     port: 8080
          #   initialDelaySeconds: 30
          # livenessProbe:
          #   httpGet:
          #     path: /health/live
          #     port: 8080
          #   initialDelaySeconds: 60
      volumes:
        - name: realm-config
          configMap:
            name: keycloak-realm-config
---
apiVersion: v1
kind: Service
metadata:
  name: localdev-keycloak
spec:
  selector:
    app: localdev-keycloak
  ports:
    - port: 8080
      targetPort: 8080
