apiVersion: v1
kind: PersistentVolume
metadata:
  name: localdev-keycloak-postgres-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/localdev-keycloak-postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: localdev-keycloak-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: localdev-keycloak-postgres
spec:
  serviceName: localdev-keycloak-postgres
  replicas: 1
  selector:
    matchLabels:
      app: localdev-keycloak-postgres
  template:
    metadata:
      labels:
        app: localdev-keycloak-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_DB
              value: keycloak
            - name: POSTGRES_USER
              value: keycloak
            - name: POSTGRES_PASSWORD
              value: keycloak
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: localdev-keycloak-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: localdev-keycloak-postgres
spec:
  selector:
    app: localdev-keycloak-postgres
  ports:
    - port: 5432
