apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: localdev-temporal-pvc
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: localdev-temporal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localdev-temporal
  template:
    metadata:
      labels:
        app: localdev-temporal
    spec:
      containers:
      - name: localdev-temporal
        image: localdev-dev/temporal-dev
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7233
        - containerPort: 8233

        env:
        - name: TEMPORAL_LOG_FORMAT
          value: pretty
        volumeMounts:
        - name: localdev-temporal-persistent-storage
          mountPath: /srv/temporal
      volumes:
      - name: localdev-temporal-persistent-storage
        persistentVolumeClaim:
          claimName: localdev-temporal-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: localdev-temporal
spec:
  type: ClusterIP
  selector:
    app: localdev-temporal
  ports:
  - port: 7233
    targetPort: 7233
    name: grpc
  - port: 8233
    targetPort: 8233
    name: ui
