apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-configmap
data:
  Caddyfile: |
    #{SITE_HOSTNAME}#:80 {
      reverse_proxy /* http://host.docker.internal:#{SITE_PORT}#
      reverse_proxy / http://host.docker.internal:#{SITE_PORT}#
    }

    #{KEYCLOAK_HOSTNAME}#:80 {
      reverse_proxy /* http://host.docker.internal:#{KEYCLOAK_PORT}#
      reverse_proxy / http://host.docker.internal:#{KEYCLOAK_PORT}#
    }

    #{S3_HOSTNAME}#:80 {
      reverse_proxy /* http://host.docker.internal:#{MINIO_PORT}#
      reverse_proxy / http://host.docker.internal:#{MINIO_PORT}#
    }

    #{MINIO_UI_HOSTNAME}#:80 {
      reverse_proxy /* http://host.docker.internal:#{MINIO_UI_PORT}#
      reverse_proxy / http://host.docker.internal:#{MINIO_UI_PORT}#
    }

