apiVersion: apps/v1
kind: Deployment
metadata:
  name: localdev-postgres
spec:
  selector:
    matchLabels:
      app: localdev-postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: localdev-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: postgres-storage
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: localdev-postgres-pvc
