apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: localdev-postgres-pvc
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
